-- ReelRamp Pro complete schema. Run in Supabase SQL Editor.
create table if not exists videos (id serial primary key,title text,description text,series_title text,episode_number integer,video_filename text,thumbnail_url text,is_premium boolean default false,is_published boolean default true,duration_seconds integer default 0,category text,bunny_video_id text,bunny_embed_url text,age_rating text default 'U/A 13+',publish_at timestamptz,created_at timestamptz default now());
create table if not exists series (id serial primary key,title text,description text,poster_url text,category text,status text,sort_order integer default 0,is_featured boolean default false,created_at timestamptz default now());
create table if not exists categories (id serial primary key,name text not null,slug text,icon text,sort_order integer default 0,is_active boolean default true);
create table if not exists banners (id serial primary key,title text,subtitle text,image_url text,cta_label text,cta_action text,is_active boolean default true,sort_order integer default 0);
create table if not exists popup_settings (id serial primary key,title text,message text,cta_label text,cta_url text,enabled boolean default true,updated_at timestamptz default now());
create table if not exists platform_settings (id serial primary key,site_name text,hero_title text,hero_subtitle text,pwa_message text,maintenance_mode boolean default false,updated_at timestamptz default now());
create table if not exists admin_settings (id serial primary key,key text not null,value jsonb,updated_at timestamptz default now());
create table if not exists legal_policies (id serial primary key,title text not null,body text,type text,version text,is_published boolean default true,updated_at timestamptz default now());
create table if not exists plans (id serial primary key,name text,price numeric,duration_days integer,features jsonb,is_active boolean default true,sort_order integer default 0);
create table if not exists users (id serial primary key,guest_id text not null,display_name text,email text,role text,is_admin boolean default false,created_at timestamptz default now());
create table if not exists subscriptions (id serial primary key,user_id text not null,plan text,status text,expires_at timestamptz,created_at timestamptz default now());
create table if not exists payments (id serial primary key,user_id text,plan_id integer,amount numeric,gateway text,status text,transaction_id text,notes text,created_at timestamptz default now());
create table if not exists watch_history (id serial primary key,user_id text,video_id integer,current_time numeric,duration numeric,completed boolean default false,updated_at timestamptz default now());
create table if not exists likes (id serial primary key,user_id text,video_id integer,created_at timestamptz default now());
create table if not exists bookmarks (id serial primary key,user_id text,video_id integer,created_at timestamptz default now());
create table if not exists video_views (id serial primary key,user_id text,video_id integer,watch_seconds numeric,completed boolean default false,device text,created_at timestamptz default now());
create table if not exists support_tickets (id serial primary key,user_id text,name text,contact text,message text,status text,created_at timestamptz default now());
create table if not exists promo_campaigns (id serial primary key,title text,subtitle text,celebrity_name text,video_filename text,poster_url text,offer_text text,cta_label text,cta_action text,placement text,show_after_seconds integer default 2,frequency_hours integer default 12,is_active boolean default true,sort_order integer default 0,start_at timestamptz,end_at timestamptz,target text,updated_at timestamptz default now());
create table if not exists notifications (id serial primary key,title text,message text,target text,is_active boolean default true,created_at timestamptz default now());
create table if not exists promo_events (id serial primary key,campaign_id integer,user_id text,event_type text,metadata jsonb,created_at timestamptz default now());
create table if not exists audit_logs (id serial primary key,actor text,action text,resource text,resource_id integer,metadata jsonb,created_at timestamptz default now());
create table if not exists referrals (id serial primary key,referrer_id text,referred_id text,code text,reward_status text,reward_amount integer default 0,created_at timestamptz default now());
create table if not exists wallet_transactions (id serial primary key,user_id text,type text,coins integer,reason text,reference_id text,created_at timestamptz default now());
create table if not exists content_reports (id serial primary key,user_id text,video_id integer,reason text,details text,status text,created_at timestamptz default now());
create table if not exists error_logs (id serial primary key,source text,message text,stack text,metadata jsonb,severity text,created_at timestamptz default now());
create table if not exists help_articles (id serial primary key,title text,body text,category text,is_published boolean default true,sort_order integer default 0,created_at timestamptz default now());
create table if not exists push_subscriptions (id serial primary key,user_id text,endpoint text,subscription jsonb,enabled boolean default true,created_at timestamptz default now());
create index if not exists idx_videos_published on videos(is_published, publish_at);
create index if not exists idx_watch_history_user on watch_history(user_id);
create index if not exists idx_subscriptions_user on subscriptions(user_id);
